version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true 
    tty: true      
    image: app-desafio-automy
    container_name: app-desafio
    ports:
      - "3000:3000"
    